### ISSUE TITLE
How does "orb $0x10, page_table + 1" in paging.S set up the first page table to point 0 to 4KiB?

### ISSUE THREAD

**Issue by liujunming** [cirosantilli/x86-bare-metal-examples#12]
https://github.com/cirosantilli/x86-bare-metal-examples/blob/b4e4c124a3c3c329dcf09a5697237ed3b216a318/paging.S#L16

Hi, Ciro Santilli:
I couldn't understand why this line code can make page 0 point to 4KiB.
Could you please add more comments here?

Thanks

**Comment by cirosantilli** [comment]
Have a look at the page table entry format from the Intel manual reproduced at: https://cirosantilli.com/x86-paging#image-x86-page-entry-format

`orb $0x10, page_table + 1` is setting bit 12 to 1.

That, in addition to the hardcoded page directory setup done at `SETUP_PAGING_4M`, makes  page 0 points to page 1, and each page id 4KiB.

Also clarified at cf4f2df43b34774b11f0ccffc8c8b975d02a35d5

**Comment by liujunming** [comment]
This issue has solved, so close it.
