### ISSUE TITLE
Any USB keyboard and mouse examples 

### ISSUE THREAD

**Issue by lonnietc** [cirosantilli/x86-bare-metal-examples#26]
Hello,

I am trying to learn about some assembly for a new OS that is being written and that will support modern hardware (Intel and AMD) that mostly uses USB keyboard and mouse.

Do you have any examples of this?

**Comment by cirosantilli** [comment]
Hi,

I don't have any examples of that by myself.

I would just try to read/copy Linux kernel.

From scratch USB support is likely to be hard I think. Not 100% sure.

**Comment by lonnietc** [comment]
Thanks so very much for answering my inquiry on this.

I actually did find an Assembly project "TatOS" that actually does show a simple USB keyboard and mouse interface:

```
https://github.com/tatimmer/tatOS
```

I was able to put the existing TatOS.img on a small USB stick and boot it up on my Intel NUC7 which has no legacy keyboard and mouse interfaces for which the keyboard worked. Was not able to get it to compile and I do not know enough about Assembly to extract out the USB parts to set up a simple demo like your examples, which I like a lot by the way as they help to understand things more.

Maybe I will keep looking at the TatOS more since it seems that I cannot locate a good and simple USB library in C/C++ that might do the job for the x86_64 platform which I need.

Thanks again and have a great day

**Comment by cirosantilli** [comment]
I see. Do leave a comment later on if you manage it.

**Comment by lonnietc** [comment]
Will keep you updated, my friend. Thanks

**Comment by cirosantilli** [comment]
Came across this BTW: https://www.youtube.com/watch?v=wdgULBpRoXk
