### ISSUE TITLE
Cannot see output from QEMU with -nographic inside vagrant Ubuntu 14.04

### ISSUE THREAD

**Issue by Townsheriff** [cirosantilli/x86-bare-metal-examples#3]
I have a vagrant box which is running ubuntu 14.04 where I compiled source code `make`, edited `Makefile` for run command `$(QEMU) -drive 'file=$(RUN_FILE),format=raw' -smp 2 -nographic` and I don't see anything in output.

Also when I try to run `make run RUN=min`.
Logs:
```
qemu-system-i386 -drive 'file=min.img,format=raw' -smp 2 -nographic
qemu: fatal: Trying to execute code outside RAM or ROM at 0x000a0000

EAX=0000ff04 EBX=00000000 ECX=00000000 EDX=00000080
ESI=00000000 EDI=00000000 EBP=00006f20 ESP=00006f20
EIP=0009ffd2 EFL=00000092 [--S-A--] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =0000 00000000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     000f68c0 00000037
IDT=     00000000 000003ff
CR0=00000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000
DR6=ffff0ff0 DR7=00000400
CCS=0000ff04 CCD=0000ffb3 CCO=ADDB
EFER=0000000000000000
FCW=037f FSW=0000 [ST=0] FTW=00 MXCSR=00001f80
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
make: *** [run] Aborted (core dumped)
```
I don't know if this is expected. 

If I try running any other image nothing happens (with or without `-nographic` argument), I don't even know If they ran and I just don't see it or it failed to start.

What I'm doing wrong here?

**Comment by cirosantilli** [comment]
Please split the Mac OS error to another issue.

**Comment by cirosantilli** [comment]
I'm not sure, but I think `-nographic` requires serial support, which is implemented for example by the Linux kernel, but not by this minimal image.

All that the hardware screen sees is a bunch of pixels, how would QEMU be able to map those to characters for the terminal without some known standard like serial?

When I run `$(QEMU) -drive 'file=$(RUN_FILE),format=raw' -smp 2 -nographic` just now on Ubuntu 16.04 QEMU 2.5.0, I simply see not output, so I don't reproduce `qemu: fatal: Trying to execute code outside RAM or ROM at 0x000a0000` and the error that follows, so I can't reproduce :-(

Try Ubuntu 16.04 to see if you can reproduce.

**Comment by Townsheriff** [comment]
Thanks, running in Ubuntu 16.04 resolved my issue.

**Comment by cirosantilli** [comment]
Awesome. Did 14.04 with a display fail, or did you go directly to 16.04 with display?

**Comment by Townsheriff** [comment]
I went directly to 16.04. Did not try ubuntu 14.04 with display. Thanks!
