### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Izzette** [cirosantilli/x86-bare-metal-examples#4]
Maybe I've just missed it, but I can't seem to find any licensing information.  You should drop a big fat LICENSE file (or UNLICENSE if you prefer) so people know if and how they can use, modify, and distribute this code.

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/x86-bare-metal-examples/blob/16f0eaf8dd0ea77239108c9aba82a4e94dc51ab5/LICENSE.md

:-)
